with tb_match as (

    select *
    from match_players

),


tb_join as (

    select *

    from tb_match as t1

    left join tb_book_player as t2
    on t1.player_id = t2.account_id

),

tb_window_flag as (

    select *,
           row_number() over (partition by player_id order by dt_ref desc) as order_dt
    from tb_join
),

tb_filter_recencia as (

    select *
    from tb_window_flag
    where order_dt = 1

),

tb_join_group as (

    select
            t1.match_id,

            avg( case when t1.isRadiant = 1 then t1.recencia end ) as recencia_r,
            avg( case when t1.isRadiant = 1 then t1.freq end ) as freq_r,
            avg( case when t1.isRadiant = 1 then t1.win_pct end ) as win_pct_r,
            avg( case when t1.isRadiant = 1 then t1.duration_avg_win end ) as duration_avg_win_r,
            avg( case when t1.isRadiant = 1 then t1.duration_avg_lose end ) as duration_avg_lose_r,
            avg( case when t1.isRadiant = 1 then t1.actions_per_min_avg end ) as actions_per_min_avg_r,
            avg( case when t1.isRadiant = 1 then t1.ancient_kills_avg end ) as ancient_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.assists_avg end ) as assists_avg_r,
            avg( case when t1.isRadiant = 1 then t1.buyback_count_avg end ) as buyback_count_avg_r,
            avg( case when t1.isRadiant = 1 then t1.courier_kills_avg end ) as courier_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.deaths_avg end ) as deaths_avg_r,
            avg( case when t1.isRadiant = 1 then t1.denies_avg end ) as denies_avg_r,
            avg( case when t1.isRadiant = 1 then t1.firstblood_claimed_avg end ) as firstblood_claimed_avg_r,
            avg( case when t1.isRadiant = 1 then t1.gold_avg end ) as gold_avg_r,
            avg( case when t1.isRadiant = 1 then t1.gold_per_min_avg end ) as gold_per_min_avg_r,
            avg( case when t1.isRadiant = 1 then t1.gold_spent_avg end ) as gold_spent_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_damage_avg end ) as hero_damage_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_healing_avg end ) as hero_healing_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_kills_avg end ) as hero_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.isRadiant_avg end ) as isRadiant_avg_r,
            avg( case when t1.isRadiant = 1 then t1.kda_avg end ) as kda_avg_r,
            avg( case when t1.isRadiant = 1 then t1.kills_per_min_avg end ) as kills_per_min_avg_r,
            avg( case when t1.isRadiant = 1 then t1.lane_efficiency_avg end ) as lane_efficiency_avg_r,
            avg( case when t1.isRadiant = 1 then t1.lane_kills_avg end ) as lane_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.last_hits_avg end ) as last_hits_avg_r,
            avg( case when t1.isRadiant = 1 then t1.level_avg end ) as level_avg_r,
            avg( case when t1.isRadiant = 1 then t1.necronomicon_kills_avg end ) as necronomicon_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.neutral_kills_avg end ) as neutral_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.observer_kills_avg end ) as observer_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.observer_uses_avg end ) as observer_uses_avg_r,
            avg( case when t1.isRadiant = 1 then t1.purchase_tpscroll_avg end ) as purchase_tpscroll_avg_r,
            avg( case when t1.isRadiant = 1 then t1.roshan_kills_avg end ) as roshan_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.sentry_kills_avg end ) as sentry_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.sentry_uses_avg end ) as sentry_uses_avg_r,
            avg( case when t1.isRadiant = 1 then t1.total_gold_avg end ) as total_gold_avg_r,
            avg( case when t1.isRadiant = 1 then t1.total_xp_avg end ) as total_xp_avg_r,
            avg( case when t1.isRadiant = 1 then t1.tower_damage_avg end ) as tower_damage_avg_r,
            avg( case when t1.isRadiant = 1 then t1.tower_kills_avg end ) as tower_kills_avg_r,
            avg( case when t1.isRadiant = 1 then t1.xp_per_min_avg end ) as xp_per_min_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_1_avg end ) as hero_1_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_2_avg end ) as hero_2_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_3_avg end ) as hero_3_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_4_avg end ) as hero_4_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_5_avg end ) as hero_5_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_6_avg end ) as hero_6_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_7_avg end ) as hero_7_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_8_avg end ) as hero_8_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_9_avg end ) as hero_9_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_10_avg end ) as hero_10_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_11_avg end ) as hero_11_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_12_avg end ) as hero_12_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_13_avg end ) as hero_13_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_14_avg end ) as hero_14_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_15_avg end ) as hero_15_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_16_avg end ) as hero_16_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_17_avg end ) as hero_17_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_18_avg end ) as hero_18_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_19_avg end ) as hero_19_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_20_avg end ) as hero_20_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_21_avg end ) as hero_21_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_22_avg end ) as hero_22_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_23_avg end ) as hero_23_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_25_avg end ) as hero_25_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_26_avg end ) as hero_26_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_27_avg end ) as hero_27_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_28_avg end ) as hero_28_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_29_avg end ) as hero_29_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_30_avg end ) as hero_30_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_31_avg end ) as hero_31_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_32_avg end ) as hero_32_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_33_avg end ) as hero_33_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_34_avg end ) as hero_34_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_35_avg end ) as hero_35_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_36_avg end ) as hero_36_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_37_avg end ) as hero_37_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_38_avg end ) as hero_38_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_39_avg end ) as hero_39_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_40_avg end ) as hero_40_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_41_avg end ) as hero_41_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_42_avg end ) as hero_42_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_43_avg end ) as hero_43_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_44_avg end ) as hero_44_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_45_avg end ) as hero_45_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_46_avg end ) as hero_46_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_47_avg end ) as hero_47_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_48_avg end ) as hero_48_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_49_avg end ) as hero_49_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_50_avg end ) as hero_50_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_51_avg end ) as hero_51_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_52_avg end ) as hero_52_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_53_avg end ) as hero_53_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_54_avg end ) as hero_54_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_55_avg end ) as hero_55_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_56_avg end ) as hero_56_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_57_avg end ) as hero_57_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_58_avg end ) as hero_58_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_59_avg end ) as hero_59_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_60_avg end ) as hero_60_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_61_avg end ) as hero_61_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_62_avg end ) as hero_62_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_63_avg end ) as hero_63_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_64_avg end ) as hero_64_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_65_avg end ) as hero_65_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_66_avg end ) as hero_66_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_67_avg end ) as hero_67_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_68_avg end ) as hero_68_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_69_avg end ) as hero_69_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_70_avg end ) as hero_70_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_71_avg end ) as hero_71_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_72_avg end ) as hero_72_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_73_avg end ) as hero_73_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_74_avg end ) as hero_74_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_75_avg end ) as hero_75_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_76_avg end ) as hero_76_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_77_avg end ) as hero_77_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_78_avg end ) as hero_78_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_79_avg end ) as hero_79_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_80_avg end ) as hero_80_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_81_avg end ) as hero_81_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_82_avg end ) as hero_82_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_83_avg end ) as hero_83_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_84_avg end ) as hero_84_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_85_avg end ) as hero_85_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_86_avg end ) as hero_86_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_87_avg end ) as hero_87_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_88_avg end ) as hero_88_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_89_avg end ) as hero_89_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_90_avg end ) as hero_90_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_91_avg end ) as hero_91_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_92_avg end ) as hero_92_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_93_avg end ) as hero_93_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_94_avg end ) as hero_94_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_95_avg end ) as hero_95_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_96_avg end ) as hero_96_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_97_avg end ) as hero_97_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_98_avg end ) as hero_98_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_99_avg end ) as hero_99_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_100_avg end ) as hero_100_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_101_avg end ) as hero_101_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_102_avg end ) as hero_102_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_103_avg end ) as hero_103_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_104_avg end ) as hero_104_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_105_avg end ) as hero_105_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_106_avg end ) as hero_106_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_107_avg end ) as hero_107_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_108_avg end ) as hero_108_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_109_avg end ) as hero_109_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_110_avg end ) as hero_110_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_111_avg end ) as hero_111_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_112_avg end ) as hero_112_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_113_avg end ) as hero_113_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_114_avg end ) as hero_114_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_119_avg end ) as hero_119_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_120_avg end ) as hero_120_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_126_avg end ) as hero_126_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_128_avg end ) as hero_128_avg_r,
            avg( case when t1.isRadiant = 1 then t1.hero_129_avg end ) as hero_129_avg_r,

            avg( case when t1.isRadiant = 0 then t1.recencia end ) as recencia_d,
            avg( case when t1.isRadiant = 0 then t1.freq end ) as freq_d,
            avg( case when t1.isRadiant = 0 then t1.win_pct end ) as win_pct_d,
            avg( case when t1.isRadiant = 0 then t1.duration_avg_win end ) as duration_avg_win_d,
            avg( case when t1.isRadiant = 0 then t1.duration_avg_lose end ) as duration_avg_lose_d,
            avg( case when t1.isRadiant = 0 then t1.actions_per_min_avg end ) as actions_per_min_avg_d,
            avg( case when t1.isRadiant = 0 then t1.ancient_kills_avg end ) as ancient_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.assists_avg end ) as assists_avg_d,
            avg( case when t1.isRadiant = 0 then t1.buyback_count_avg end ) as buyback_count_avg_d,
            avg( case when t1.isRadiant = 0 then t1.courier_kills_avg end ) as courier_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.deaths_avg end ) as deaths_avg_d,
            avg( case when t1.isRadiant = 0 then t1.denies_avg end ) as denies_avg_d,
            avg( case when t1.isRadiant = 0 then t1.firstblood_claimed_avg end ) as firstblood_claimed_avg_d,
            avg( case when t1.isRadiant = 0 then t1.gold_avg end ) as gold_avg_d,
            avg( case when t1.isRadiant = 0 then t1.gold_per_min_avg end ) as gold_per_min_avg_d,
            avg( case when t1.isRadiant = 0 then t1.gold_spent_avg end ) as gold_spent_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_damage_avg end ) as hero_damage_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_healing_avg end ) as hero_healing_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_kills_avg end ) as hero_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.isRadiant_avg end ) as isRadiant_avg_d,
            avg( case when t1.isRadiant = 0 then t1.kda_avg end ) as kda_avg_d,
            avg( case when t1.isRadiant = 0 then t1.kills_per_min_avg end ) as kills_per_min_avg_d,
            avg( case when t1.isRadiant = 0 then t1.lane_efficiency_avg end ) as lane_efficiency_avg_d,
            avg( case when t1.isRadiant = 0 then t1.lane_kills_avg end ) as lane_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.last_hits_avg end ) as last_hits_avg_d,
            avg( case when t1.isRadiant = 0 then t1.level_avg end ) as level_avg_d,
            avg( case when t1.isRadiant = 0 then t1.necronomicon_kills_avg end ) as necronomicon_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.neutral_kills_avg end ) as neutral_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.observer_kills_avg end ) as observer_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.observer_uses_avg end ) as observer_uses_avg_d,
            avg( case when t1.isRadiant = 0 then t1.purchase_tpscroll_avg end ) as purchase_tpscroll_avg_d,
            avg( case when t1.isRadiant = 0 then t1.roshan_kills_avg end ) as roshan_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.sentry_kills_avg end ) as sentry_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.sentry_uses_avg end ) as sentry_uses_avg_d,
            avg( case when t1.isRadiant = 0 then t1.total_gold_avg end ) as total_gold_avg_d,
            avg( case when t1.isRadiant = 0 then t1.total_xp_avg end ) as total_xp_avg_d,
            avg( case when t1.isRadiant = 0 then t1.tower_damage_avg end ) as tower_damage_avg_d,
            avg( case when t1.isRadiant = 0 then t1.tower_kills_avg end ) as tower_kills_avg_d,
            avg( case when t1.isRadiant = 0 then t1.xp_per_min_avg end ) as xp_per_min_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_1_avg end ) as hero_1_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_2_avg end ) as hero_2_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_3_avg end ) as hero_3_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_4_avg end ) as hero_4_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_5_avg end ) as hero_5_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_6_avg end ) as hero_6_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_7_avg end ) as hero_7_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_8_avg end ) as hero_8_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_9_avg end ) as hero_9_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_10_avg end ) as hero_10_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_11_avg end ) as hero_11_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_12_avg end ) as hero_12_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_13_avg end ) as hero_13_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_14_avg end ) as hero_14_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_15_avg end ) as hero_15_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_16_avg end ) as hero_16_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_17_avg end ) as hero_17_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_18_avg end ) as hero_18_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_19_avg end ) as hero_19_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_20_avg end ) as hero_20_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_21_avg end ) as hero_21_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_22_avg end ) as hero_22_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_23_avg end ) as hero_23_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_25_avg end ) as hero_25_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_26_avg end ) as hero_26_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_27_avg end ) as hero_27_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_28_avg end ) as hero_28_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_29_avg end ) as hero_29_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_30_avg end ) as hero_30_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_31_avg end ) as hero_31_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_32_avg end ) as hero_32_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_33_avg end ) as hero_33_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_34_avg end ) as hero_34_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_35_avg end ) as hero_35_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_36_avg end ) as hero_36_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_37_avg end ) as hero_37_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_38_avg end ) as hero_38_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_39_avg end ) as hero_39_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_40_avg end ) as hero_40_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_41_avg end ) as hero_41_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_42_avg end ) as hero_42_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_43_avg end ) as hero_43_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_44_avg end ) as hero_44_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_45_avg end ) as hero_45_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_46_avg end ) as hero_46_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_47_avg end ) as hero_47_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_48_avg end ) as hero_48_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_49_avg end ) as hero_49_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_50_avg end ) as hero_50_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_51_avg end ) as hero_51_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_52_avg end ) as hero_52_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_53_avg end ) as hero_53_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_54_avg end ) as hero_54_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_55_avg end ) as hero_55_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_56_avg end ) as hero_56_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_57_avg end ) as hero_57_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_58_avg end ) as hero_58_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_59_avg end ) as hero_59_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_60_avg end ) as hero_60_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_61_avg end ) as hero_61_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_62_avg end ) as hero_62_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_63_avg end ) as hero_63_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_64_avg end ) as hero_64_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_65_avg end ) as hero_65_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_66_avg end ) as hero_66_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_67_avg end ) as hero_67_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_68_avg end ) as hero_68_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_69_avg end ) as hero_69_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_70_avg end ) as hero_70_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_71_avg end ) as hero_71_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_72_avg end ) as hero_72_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_73_avg end ) as hero_73_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_74_avg end ) as hero_74_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_75_avg end ) as hero_75_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_76_avg end ) as hero_76_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_77_avg end ) as hero_77_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_78_avg end ) as hero_78_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_79_avg end ) as hero_79_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_80_avg end ) as hero_80_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_81_avg end ) as hero_81_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_82_avg end ) as hero_82_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_83_avg end ) as hero_83_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_84_avg end ) as hero_84_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_85_avg end ) as hero_85_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_86_avg end ) as hero_86_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_87_avg end ) as hero_87_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_88_avg end ) as hero_88_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_89_avg end ) as hero_89_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_90_avg end ) as hero_90_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_91_avg end ) as hero_91_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_92_avg end ) as hero_92_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_93_avg end ) as hero_93_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_94_avg end ) as hero_94_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_95_avg end ) as hero_95_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_96_avg end ) as hero_96_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_97_avg end ) as hero_97_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_98_avg end ) as hero_98_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_99_avg end ) as hero_99_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_100_avg end ) as hero_100_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_101_avg end ) as hero_101_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_102_avg end ) as hero_102_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_103_avg end ) as hero_103_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_104_avg end ) as hero_104_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_105_avg end ) as hero_105_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_106_avg end ) as hero_106_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_107_avg end ) as hero_107_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_108_avg end ) as hero_108_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_109_avg end ) as hero_109_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_110_avg end ) as hero_110_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_111_avg end ) as hero_111_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_112_avg end ) as hero_112_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_113_avg end ) as hero_113_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_114_avg end ) as hero_114_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_119_avg end ) as hero_119_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_120_avg end ) as hero_120_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_126_avg end ) as hero_126_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_128_avg end ) as hero_128_avg_d,
            avg( case when t1.isRadiant = 0 then t1.hero_129_avg end ) as hero_129_avg_d

    from tb_filter_recencia as t1
    group by t1.match_id

)

select * from tb_join_group;