version: "3"

volumes:
  mongodb-data:

services:
  mongodb:
    container_name: mongo-dota
    image: mongo:3
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: python-dota
    restart: unless-stopped
    volumes:
      - .:/root
    links:
      - mongodb
