version: "3"

volumes:
  mariadb-data:
  mongodb-data:

services:
  mongodb:
    container_name: mongo-dota
    image: mongo:3
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  mariadb:
    container_name: maria-dota
    image: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=teomewhy
    ports:
      - "3306:3306"

  python:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: python-dota
    restart: unless-stopped
    volumes:
      - .:/root
    links:
      - mongodb
      - mariadb
