select account_id,
        count(distinct match_id) as freq,
        avg( win ) as win_pct,
        sum( win ) as win_qtd,
        avg(duration) / 60 as duration_avg,

        avg(case when win = 1 then duration end) / 60 as duration_avg_win,
        avg(case when win = 0 then duration end) / 60 as duration_avg_lose,

        sum(duration) / 60 as duration_qtd,

        avg( actions_per_min ) as  actions_per_min_avg,
        avg( ancient_kills ) as  ancient_kills_avg,
        avg( assists ) as  assists_avg,
        avg( buyback_count ) as  buyback_count_avg,
        avg( courier_kills ) as  courier_kills_avg,
        avg( deaths ) as  deaths_avg,
        avg( denies ) as  denies_avg,
        avg( firstblood_claimed ) as  firstblood_claimed_avg,
        avg( gold ) as  gold_avg,
        avg( gold_per_min ) as  gold_per_min_avg,
        avg( gold_spent ) as  gold_spent_avg,
        avg( hero_damage ) as  hero_damage_avg,
        avg( hero_healing ) as  hero_healing_avg,
        avg( hero_kills ) as  hero_kills_avg,
        avg( isRadiant ) as  isRadiant_avg,
        avg( kda ) as  kda_avg,
        avg( kills_per_min ) as  kills_per_min_avg,
        avg( lane ) as  lane_avg,
        avg( lane_efficiency ) as  lane_efficiency_avg,
        avg( lane_efficiency_pct ) as  lane_efficiency_pct_avg,
        avg( lane_kills ) as  lane_kills_avg,
        avg( last_hits ) as  last_hits_avg,
        avg( level ) as  level_avg,
        avg( necronomicon_kills ) as  necronomicon_kills_avg,
        avg( neutral_kills ) as  neutral_kills_avg,
        avg( observer_kills ) as  observer_kills_avg,
        avg( observer_uses ) as  observer_uses_avg,
        avg( purchase_tpscroll ) as  purchase_tpscroll_avg,
        avg( rank_tier ) as  rank_tier_avg,
        avg( roshan_kills ) as  roshan_kills_avg,
        avg( sentry_kills ) as  sentry_kills_avg,
        avg( sentry_uses ) as  sentry_uses_avg,
        avg( start_time ) as  start_time_avg,
        avg( total_gold ) as  total_gold_avg,
        avg( total_xp ) as  total_xp_avg,
        avg( tower_damage ) as  tower_damage_avg,
        avg( tower_kills ) as  tower_kills_avg,
        avg( xp_per_min ) as  xp_per_min_avg,

        sum( ancient_kills ) as  ancient_kills_sum,
        sum( assists ) as  assists_sum,
        sum( buyback_count ) as  buyback_count_sum,
        sum( courier_kills ) as  courier_kills_sum,
        sum( deaths ) as  deaths_sum,
        sum( denies ) as  denies_sum,
        sum( firstblood_claimed ) as  firstblood_claimed_sum,
        sum( gold ) as  gold_sum,
        sum( gold_spent ) as  gold_spent_sum,
        sum( hero_damage ) as  hero_damage_sum,
        sum( hero_healing ) as  hero_healing_sum,
        sum( hero_kills ) as  hero_kills_sum,
        sum( isRadiant ) as  isRadiant_sum,
        sum( lane_kills ) as  lane_kills_sum,
        sum( last_hits ) as  last_hits_sum,
        sum( necronomicon_kills ) as  necronomicon_kills_sum,
        sum( neutral_kills ) as  neutral_kills_sum,
        sum( observer_kills ) as  observer_kills_sum,
        sum( observer_uses ) as  observer_uses_sum,
        sum( purchase_tpscroll ) as  purchase_tpscroll_sum,
        sum( rank_tier ) as  rank_tier_sum,
        sum( roshan_kills ) as  roshan_kills_sum,
        sum( sentry_kills ) as  sentry_kills_sum,
        sum( sentry_uses ) as  sentry_uses_sum,
        sum( start_time ) as  start_time_sum,
        sum( total_gold ) as  total_gold_sum,
        sum( total_xp ) as  total_xp_sum,
        sum( tower_damage ) as  tower_damage_sum,
        sum( tower_kills ) as  tower_kills_sum,
        sum( xp_per_min ) as  xp_per_min_sum,

        sum(case when hero_id = 1 then 1 else 0 end) as hero_1_qtd,
        sum(case when hero_id = 2 then 1 else 0 end) as hero_2_qtd,
        sum(case when hero_id = 3 then 1 else 0 end) as hero_3_qtd,
        sum(case when hero_id = 4 then 1 else 0 end) as hero_4_qtd,
        sum(case when hero_id = 5 then 1 else 0 end) as hero_5_qtd,
        sum(case when hero_id = 6 then 1 else 0 end) as hero_6_qtd,
        sum(case when hero_id = 7 then 1 else 0 end) as hero_7_qtd,
        sum(case when hero_id = 8 then 1 else 0 end) as hero_8_qtd,
        sum(case when hero_id = 9 then 1 else 0 end) as hero_9_qtd,
        sum(case when hero_id = 10 then 1 else 0 end) as hero_10_qtd,
        sum(case when hero_id = 11 then 1 else 0 end) as hero_11_qtd,
        sum(case when hero_id = 12 then 1 else 0 end) as hero_12_qtd,
        sum(case when hero_id = 13 then 1 else 0 end) as hero_13_qtd,
        sum(case when hero_id = 14 then 1 else 0 end) as hero_14_qtd,
        sum(case when hero_id = 15 then 1 else 0 end) as hero_15_qtd,
        sum(case when hero_id = 16 then 1 else 0 end) as hero_16_qtd,
        sum(case when hero_id = 17 then 1 else 0 end) as hero_17_qtd,
        sum(case when hero_id = 18 then 1 else 0 end) as hero_18_qtd,
        sum(case when hero_id = 19 then 1 else 0 end) as hero_19_qtd,
        sum(case when hero_id = 20 then 1 else 0 end) as hero_20_qtd,
        sum(case when hero_id = 21 then 1 else 0 end) as hero_21_qtd,
        sum(case when hero_id = 22 then 1 else 0 end) as hero_22_qtd,
        sum(case when hero_id = 23 then 1 else 0 end) as hero_23_qtd,
        sum(case when hero_id = 25 then 1 else 0 end) as hero_25_qtd,
        sum(case when hero_id = 26 then 1 else 0 end) as hero_26_qtd,
        sum(case when hero_id = 27 then 1 else 0 end) as hero_27_qtd,
        sum(case when hero_id = 28 then 1 else 0 end) as hero_28_qtd,
        sum(case when hero_id = 29 then 1 else 0 end) as hero_29_qtd,
        sum(case when hero_id = 30 then 1 else 0 end) as hero_30_qtd,
        sum(case when hero_id = 31 then 1 else 0 end) as hero_31_qtd,
        sum(case when hero_id = 32 then 1 else 0 end) as hero_32_qtd,
        sum(case when hero_id = 33 then 1 else 0 end) as hero_33_qtd,
        sum(case when hero_id = 34 then 1 else 0 end) as hero_34_qtd,
        sum(case when hero_id = 35 then 1 else 0 end) as hero_35_qtd,
        sum(case when hero_id = 36 then 1 else 0 end) as hero_36_qtd,
        sum(case when hero_id = 37 then 1 else 0 end) as hero_37_qtd,
        sum(case when hero_id = 38 then 1 else 0 end) as hero_38_qtd,
        sum(case when hero_id = 39 then 1 else 0 end) as hero_39_qtd,
        sum(case when hero_id = 40 then 1 else 0 end) as hero_40_qtd,
        sum(case when hero_id = 41 then 1 else 0 end) as hero_41_qtd,
        sum(case when hero_id = 42 then 1 else 0 end) as hero_42_qtd,
        sum(case when hero_id = 43 then 1 else 0 end) as hero_43_qtd,
        sum(case when hero_id = 44 then 1 else 0 end) as hero_44_qtd,
        sum(case when hero_id = 45 then 1 else 0 end) as hero_45_qtd,
        sum(case when hero_id = 46 then 1 else 0 end) as hero_46_qtd,
        sum(case when hero_id = 47 then 1 else 0 end) as hero_47_qtd,
        sum(case when hero_id = 48 then 1 else 0 end) as hero_48_qtd,
        sum(case when hero_id = 49 then 1 else 0 end) as hero_49_qtd,
        sum(case when hero_id = 50 then 1 else 0 end) as hero_50_qtd,
        sum(case when hero_id = 51 then 1 else 0 end) as hero_51_qtd,
        sum(case when hero_id = 52 then 1 else 0 end) as hero_52_qtd,
        sum(case when hero_id = 53 then 1 else 0 end) as hero_53_qtd,
        sum(case when hero_id = 54 then 1 else 0 end) as hero_54_qtd,
        sum(case when hero_id = 55 then 1 else 0 end) as hero_55_qtd,
        sum(case when hero_id = 56 then 1 else 0 end) as hero_56_qtd,
        sum(case when hero_id = 57 then 1 else 0 end) as hero_57_qtd,
        sum(case when hero_id = 58 then 1 else 0 end) as hero_58_qtd,
        sum(case when hero_id = 59 then 1 else 0 end) as hero_59_qtd,
        sum(case when hero_id = 60 then 1 else 0 end) as hero_60_qtd,
        sum(case when hero_id = 61 then 1 else 0 end) as hero_61_qtd,
        sum(case when hero_id = 62 then 1 else 0 end) as hero_62_qtd,
        sum(case when hero_id = 63 then 1 else 0 end) as hero_63_qtd,
        sum(case when hero_id = 64 then 1 else 0 end) as hero_64_qtd,
        sum(case when hero_id = 65 then 1 else 0 end) as hero_65_qtd,
        sum(case when hero_id = 66 then 1 else 0 end) as hero_66_qtd,
        sum(case when hero_id = 67 then 1 else 0 end) as hero_67_qtd,
        sum(case when hero_id = 68 then 1 else 0 end) as hero_68_qtd,
        sum(case when hero_id = 69 then 1 else 0 end) as hero_69_qtd,
        sum(case when hero_id = 70 then 1 else 0 end) as hero_70_qtd,
        sum(case when hero_id = 71 then 1 else 0 end) as hero_71_qtd,
        sum(case when hero_id = 72 then 1 else 0 end) as hero_72_qtd,
        sum(case when hero_id = 73 then 1 else 0 end) as hero_73_qtd,
        sum(case when hero_id = 74 then 1 else 0 end) as hero_74_qtd,
        sum(case when hero_id = 75 then 1 else 0 end) as hero_75_qtd,
        sum(case when hero_id = 76 then 1 else 0 end) as hero_76_qtd,
        sum(case when hero_id = 77 then 1 else 0 end) as hero_77_qtd,
        sum(case when hero_id = 78 then 1 else 0 end) as hero_78_qtd,
        sum(case when hero_id = 79 then 1 else 0 end) as hero_79_qtd,
        sum(case when hero_id = 80 then 1 else 0 end) as hero_80_qtd,
        sum(case when hero_id = 81 then 1 else 0 end) as hero_81_qtd,
        sum(case when hero_id = 82 then 1 else 0 end) as hero_82_qtd,
        sum(case when hero_id = 83 then 1 else 0 end) as hero_83_qtd,
        sum(case when hero_id = 84 then 1 else 0 end) as hero_84_qtd,
        sum(case when hero_id = 85 then 1 else 0 end) as hero_85_qtd,
        sum(case when hero_id = 86 then 1 else 0 end) as hero_86_qtd,
        sum(case when hero_id = 87 then 1 else 0 end) as hero_87_qtd,
        sum(case when hero_id = 88 then 1 else 0 end) as hero_88_qtd,
        sum(case when hero_id = 89 then 1 else 0 end) as hero_89_qtd,
        sum(case when hero_id = 90 then 1 else 0 end) as hero_90_qtd,
        sum(case when hero_id = 91 then 1 else 0 end) as hero_91_qtd,
        sum(case when hero_id = 92 then 1 else 0 end) as hero_92_qtd,
        sum(case when hero_id = 93 then 1 else 0 end) as hero_93_qtd,
        sum(case when hero_id = 94 then 1 else 0 end) as hero_94_qtd,
        sum(case when hero_id = 95 then 1 else 0 end) as hero_95_qtd,
        sum(case when hero_id = 96 then 1 else 0 end) as hero_96_qtd,
        sum(case when hero_id = 97 then 1 else 0 end) as hero_97_qtd,
        sum(case when hero_id = 98 then 1 else 0 end) as hero_98_qtd,
        sum(case when hero_id = 99 then 1 else 0 end) as hero_99_qtd,
        sum(case when hero_id = 100 then 1 else 0 end) as hero_100_qtd,
        sum(case when hero_id = 101 then 1 else 0 end) as hero_101_qtd,
        sum(case when hero_id = 102 then 1 else 0 end) as hero_102_qtd,
        sum(case when hero_id = 103 then 1 else 0 end) as hero_103_qtd,
        sum(case when hero_id = 104 then 1 else 0 end) as hero_104_qtd,
        sum(case when hero_id = 105 then 1 else 0 end) as hero_105_qtd,
        sum(case when hero_id = 106 then 1 else 0 end) as hero_106_qtd,
        sum(case when hero_id = 107 then 1 else 0 end) as hero_107_qtd,
        sum(case when hero_id = 108 then 1 else 0 end) as hero_108_qtd,
        sum(case when hero_id = 109 then 1 else 0 end) as hero_109_qtd,
        sum(case when hero_id = 110 then 1 else 0 end) as hero_110_qtd,
        sum(case when hero_id = 111 then 1 else 0 end) as hero_111_qtd,
        sum(case when hero_id = 112 then 1 else 0 end) as hero_112_qtd,
        sum(case when hero_id = 113 then 1 else 0 end) as hero_113_qtd,
        sum(case when hero_id = 114 then 1 else 0 end) as hero_114_qtd,
        sum(case when hero_id = 119 then 1 else 0 end) as hero_119_qtd,
        sum(case when hero_id = 120 then 1 else 0 end) as hero_120_qtd,
        sum(case when hero_id = 121 then 1 else 0 end) as hero_121_qtd,
        sum(case when hero_id = 126 then 1 else 0 end) as hero_126_qtd,
        sum(case when hero_id = 128 then 1 else 0 end) as hero_128_qtd,
        sum(case when hero_id = 129 then 1 else 0 end) as hero_129_qtd,

        CAST( avg(case when hero_id = 1 then 1 else 0 end) as double) as hero_1_avg,
        CAST( avg(case when hero_id = 2 then 1 else 0 end) as double) as hero_2_avg,
        CAST( avg(case when hero_id = 3 then 1 else 0 end) as double) as hero_3_avg,
        CAST( avg(case when hero_id = 4 then 1 else 0 end) as double) as hero_4_avg,
        CAST( avg(case when hero_id = 5 then 1 else 0 end) as double) as hero_5_avg,
        CAST( avg(case when hero_id = 6 then 1 else 0 end) as double) as hero_6_avg,
        CAST( avg(case when hero_id = 7 then 1 else 0 end) as double) as hero_7_avg,
        CAST( avg(case when hero_id = 8 then 1 else 0 end) as double) as hero_8_avg,
        CAST( avg(case when hero_id = 9 then 1 else 0 end) as double) as hero_9_avg,
        CAST( avg(case when hero_id = 10 then 1 else 0 end) as double) as hero_10_avg,
        CAST( avg(case when hero_id = 11 then 1 else 0 end) as double) as hero_11_avg,
        CAST( avg(case when hero_id = 12 then 1 else 0 end) as double) as hero_12_avg,
        CAST( avg(case when hero_id = 13 then 1 else 0 end) as double) as hero_13_avg,
        CAST( avg(case when hero_id = 14 then 1 else 0 end) as double) as hero_14_avg,
        CAST( avg(case when hero_id = 15 then 1 else 0 end) as double) as hero_15_avg,
        CAST( avg(case when hero_id = 16 then 1 else 0 end) as double) as hero_16_avg,
        CAST( avg(case when hero_id = 17 then 1 else 0 end) as double) as hero_17_avg,
        CAST( avg(case when hero_id = 18 then 1 else 0 end) as double) as hero_18_avg,
        CAST( avg(case when hero_id = 19 then 1 else 0 end) as double) as hero_19_avg,
        CAST( avg(case when hero_id = 20 then 1 else 0 end) as double) as hero_20_avg,
        CAST( avg(case when hero_id = 21 then 1 else 0 end) as double) as hero_21_avg,
        CAST( avg(case when hero_id = 22 then 1 else 0 end) as double) as hero_22_avg,
        CAST( avg(case when hero_id = 23 then 1 else 0 end) as double) as hero_23_avg,
        CAST( avg(case when hero_id = 25 then 1 else 0 end) as double) as hero_25_avg,
        CAST( avg(case when hero_id = 26 then 1 else 0 end) as double) as hero_26_avg,
        CAST( avg(case when hero_id = 27 then 1 else 0 end) as double) as hero_27_avg,
        CAST( avg(case when hero_id = 28 then 1 else 0 end) as double) as hero_28_avg,
        CAST( avg(case when hero_id = 29 then 1 else 0 end) as double) as hero_29_avg,
        CAST( avg(case when hero_id = 30 then 1 else 0 end) as double) as hero_30_avg,
        CAST( avg(case when hero_id = 31 then 1 else 0 end) as double) as hero_31_avg,
        CAST( avg(case when hero_id = 32 then 1 else 0 end) as double) as hero_32_avg,
        CAST( avg(case when hero_id = 33 then 1 else 0 end) as double) as hero_33_avg,
        CAST( avg(case when hero_id = 34 then 1 else 0 end) as double) as hero_34_avg,
        CAST( avg(case when hero_id = 35 then 1 else 0 end) as double) as hero_35_avg,
        CAST( avg(case when hero_id = 36 then 1 else 0 end) as double) as hero_36_avg,
        CAST( avg(case when hero_id = 37 then 1 else 0 end) as double) as hero_37_avg,
        CAST( avg(case when hero_id = 38 then 1 else 0 end) as double) as hero_38_avg,
        CAST( avg(case when hero_id = 39 then 1 else 0 end) as double) as hero_39_avg,
        CAST( avg(case when hero_id = 40 then 1 else 0 end) as double) as hero_40_avg,
        CAST( avg(case when hero_id = 41 then 1 else 0 end) as double) as hero_41_avg,
        CAST( avg(case when hero_id = 42 then 1 else 0 end) as double) as hero_42_avg,
        CAST( avg(case when hero_id = 43 then 1 else 0 end) as double) as hero_43_avg,
        CAST( avg(case when hero_id = 44 then 1 else 0 end) as double) as hero_44_avg,
        CAST( avg(case when hero_id = 45 then 1 else 0 end) as double) as hero_45_avg,
        CAST( avg(case when hero_id = 46 then 1 else 0 end) as double) as hero_46_avg,
        CAST( avg(case when hero_id = 47 then 1 else 0 end) as double) as hero_47_avg,
        CAST( avg(case when hero_id = 48 then 1 else 0 end) as double) as hero_48_avg,
        CAST( avg(case when hero_id = 49 then 1 else 0 end) as double) as hero_49_avg,
        CAST( avg(case when hero_id = 50 then 1 else 0 end) as double) as hero_50_avg,
        CAST( avg(case when hero_id = 51 then 1 else 0 end) as double) as hero_51_avg,
        CAST( avg(case when hero_id = 52 then 1 else 0 end) as double) as hero_52_avg,
        CAST( avg(case when hero_id = 53 then 1 else 0 end) as double) as hero_53_avg,
        CAST( avg(case when hero_id = 54 then 1 else 0 end) as double) as hero_54_avg,
        CAST( avg(case when hero_id = 55 then 1 else 0 end) as double) as hero_55_avg,
        CAST( avg(case when hero_id = 56 then 1 else 0 end) as double) as hero_56_avg,
        CAST( avg(case when hero_id = 57 then 1 else 0 end) as double) as hero_57_avg,
        CAST( avg(case when hero_id = 58 then 1 else 0 end) as double) as hero_58_avg,
        CAST( avg(case when hero_id = 59 then 1 else 0 end) as double) as hero_59_avg,
        CAST( avg(case when hero_id = 60 then 1 else 0 end) as double) as hero_60_avg,
        CAST( avg(case when hero_id = 61 then 1 else 0 end) as double) as hero_61_avg,
        CAST( avg(case when hero_id = 62 then 1 else 0 end) as double) as hero_62_avg,
        CAST( avg(case when hero_id = 63 then 1 else 0 end) as double) as hero_63_avg,
        CAST( avg(case when hero_id = 64 then 1 else 0 end) as double) as hero_64_avg,
        CAST( avg(case when hero_id = 65 then 1 else 0 end) as double) as hero_65_avg,
        CAST( avg(case when hero_id = 66 then 1 else 0 end) as double) as hero_66_avg,
        CAST( avg(case when hero_id = 67 then 1 else 0 end) as double) as hero_67_avg,
        CAST( avg(case when hero_id = 68 then 1 else 0 end) as double) as hero_68_avg,
        CAST( avg(case when hero_id = 69 then 1 else 0 end) as double) as hero_69_avg,
        CAST( avg(case when hero_id = 70 then 1 else 0 end) as double) as hero_70_avg,
        CAST( avg(case when hero_id = 71 then 1 else 0 end) as double) as hero_71_avg,
        CAST( avg(case when hero_id = 72 then 1 else 0 end) as double) as hero_72_avg,
        CAST( avg(case when hero_id = 73 then 1 else 0 end) as double) as hero_73_avg,
        CAST( avg(case when hero_id = 74 then 1 else 0 end) as double) as hero_74_avg,
        CAST( avg(case when hero_id = 75 then 1 else 0 end) as double) as hero_75_avg,
        CAST( avg(case when hero_id = 76 then 1 else 0 end) as double) as hero_76_avg,
        CAST( avg(case when hero_id = 77 then 1 else 0 end) as double) as hero_77_avg,
        CAST( avg(case when hero_id = 78 then 1 else 0 end) as double) as hero_78_avg,
        CAST( avg(case when hero_id = 79 then 1 else 0 end) as double) as hero_79_avg,
        CAST( avg(case when hero_id = 80 then 1 else 0 end) as double) as hero_80_avg,
        CAST( avg(case when hero_id = 81 then 1 else 0 end) as double) as hero_81_avg,
        CAST( avg(case when hero_id = 82 then 1 else 0 end) as double) as hero_82_avg,
        CAST( avg(case when hero_id = 83 then 1 else 0 end) as double) as hero_83_avg,
        CAST( avg(case when hero_id = 84 then 1 else 0 end) as double) as hero_84_avg,
        CAST( avg(case when hero_id = 85 then 1 else 0 end) as double) as hero_85_avg,
        CAST( avg(case when hero_id = 86 then 1 else 0 end) as double) as hero_86_avg,
        CAST( avg(case when hero_id = 87 then 1 else 0 end) as double) as hero_87_avg,
        CAST( avg(case when hero_id = 88 then 1 else 0 end) as double) as hero_88_avg,
        CAST( avg(case when hero_id = 89 then 1 else 0 end) as double) as hero_89_avg,
        CAST( avg(case when hero_id = 90 then 1 else 0 end) as double) as hero_90_avg,
        CAST( avg(case when hero_id = 91 then 1 else 0 end) as double) as hero_91_avg,
        CAST( avg(case when hero_id = 92 then 1 else 0 end) as double) as hero_92_avg,
        CAST( avg(case when hero_id = 93 then 1 else 0 end) as double) as hero_93_avg,
        CAST( avg(case when hero_id = 94 then 1 else 0 end) as double) as hero_94_avg,
        CAST( avg(case when hero_id = 95 then 1 else 0 end) as double) as hero_95_avg,
        CAST( avg(case when hero_id = 96 then 1 else 0 end) as double) as hero_96_avg,
        CAST( avg(case when hero_id = 97 then 1 else 0 end) as double) as hero_97_avg,
        CAST( avg(case when hero_id = 98 then 1 else 0 end) as double) as hero_98_avg,
        CAST( avg(case when hero_id = 99 then 1 else 0 end) as double) as hero_99_avg,
        CAST( avg(case when hero_id = 100 then 1 else 0 end) as double) as hero_100_avg,
        CAST( avg(case when hero_id = 101 then 1 else 0 end) as double) as hero_101_avg,
        CAST( avg(case when hero_id = 102 then 1 else 0 end) as double) as hero_102_avg,
        CAST( avg(case when hero_id = 103 then 1 else 0 end) as double) as hero_103_avg,
        CAST( avg(case when hero_id = 104 then 1 else 0 end) as double) as hero_104_avg,
        CAST( avg(case when hero_id = 105 then 1 else 0 end) as double) as hero_105_avg,
        CAST( avg(case when hero_id = 106 then 1 else 0 end) as double) as hero_106_avg,
        CAST( avg(case when hero_id = 107 then 1 else 0 end) as double) as hero_107_avg,
        CAST( avg(case when hero_id = 108 then 1 else 0 end) as double) as hero_108_avg,
        CAST( avg(case when hero_id = 109 then 1 else 0 end) as double) as hero_109_avg,
        CAST( avg(case when hero_id = 110 then 1 else 0 end) as double) as hero_110_avg,
        CAST( avg(case when hero_id = 111 then 1 else 0 end) as double) as hero_111_avg,
        CAST( avg(case when hero_id = 112 then 1 else 0 end) as double) as hero_112_avg,
        CAST( avg(case when hero_id = 113 then 1 else 0 end) as double) as hero_113_avg,
        CAST( avg(case when hero_id = 114 then 1 else 0 end) as double) as hero_114_avg,
        CAST( avg(case when hero_id = 119 then 1 else 0 end) as double) as hero_119_avg,
        CAST( avg(case when hero_id = 120 then 1 else 0 end) as double) as hero_120_avg,
        CAST( avg(case when hero_id = 126 then 1 else 0 end) as double) as hero_126_avg,
        CAST( avg(case when hero_id = 128 then 1 else 0 end) as double) as hero_128_avg,
        CAST( avg(case when hero_id = 129 then 1 else 0 end) as double) as hero_129_avg

from tb_match_player

where dt_match >= ADDDATE('2021-02-25' , INTERVAL -6 MONTH)
and game_mode = 02

group by account_id